# ----------------------------------------------
# Devops Python App Deployment
# ----------------------------------------------
# Defines the Version of Docker Compose Used
version: "3.9"
# Lists all deployed services
# For us the service web only runs the container we created (in this case the one from my docker account)
# and it forwards the container port 5000 (inside docker) to port 80 on our system 
# (this is where we can reach it).
services:
  web:
    image: sgtmate/devops:v0.0.1
    ports: 
      - "80:5000"

