- hosts: all
  become: true
  environment: 
    FLASK_APP: /vagrant/app.py

  tasks: 
  - name: Update Server
    ansible.builtin.apt:
      name: python3-pip
      update_cache: yes

  - name: Install Requirements
    ansible.builtin.pip:
      requirements: /vagrant/requirements.txt

  - name: Start WebApp
    shell: "python3 -m flask run --host=0.0.0.0"
    